sampler.settings:
  type: config_object
  label: 'Sampler settings'
  mapping:
    supported_entity_types:
      type: sequence
      label: 'Entity Types'
      sequence:
        type: string
        label: 'Entity Type'
    supported_field_types:
      type: sequence
      label: 'Field Types'
      sequence:
        type: string
        label: 'Field Type'
